class_name StatusEffectTag

enum {
	Enraged,
	ItemPowerUp,
	Discord,
	HeckinGoodSong,
	FocusKi,
	ArmadilloStance,
	ChikaraPanchi,
	Crustify,
	GooTrap,
	BrightSparkles,
	RaiseEarth,
	RockWall,
	Burning,
	DesperateKick,
	AngryHatlessMushboy,
	Stalk,
	HopAround,
	Swoop,
	WingAttack,
	Sparkles,
	AnOkaySong,
	Bounce,
	Poison,
	Sleep,
	Smelly,
	Disappeared,
	ReappearedBuff,
	MandolinPlay,
	ConfusionForSwordBlobbo,
	FishguyBananBazookaCharge,
	Fear,
	BlobboAbsorbedPunch,
	HeartbrokenKoboldio,
	BananBruised,
	MushboyPostMesmerized,
	HarpyEnamored,
	BoostAgainstPaladinWhiteMage,
	SparkleFromRare,
	HunterGooedUp,
	MonkRockBreakingRoutine, # to add the MonkBreaksRock effect
	MonkBreaksRocks, # to add 5% more power
}
